# add logging and health check
services:
  db:
    image: postgres:18
    environment:
      - POSTGRES_DB=temp
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - temp_db:/var/lib/postgresql
    networks:
      - default

volumes:
  temp_db:
