services:
  db:
    expose:
      - 5432

  backend:
    image: osakasfavoritedev/testdep-backend:latest
    container_name: testdep-backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    expose:
      - 8080
    depends_on:
      - db
    networks:
      - caddy-network
      - default

networks:
  caddy-network:
    name: caddy-network
    external: true
