# add logging and health check
services:
  db:
    image: postgres:18
    environment:
      - POSTGRES_DB=temp
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - temp_db:/var/lib/postgresql
    networks:
      - default
    expose:
      - 5432
  backend:
    image: testdep-backend:local
    container_name: testdep-backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    expose:
      - 8080
    networks:
      - default
      - caddy-network

volumes:
  temp_db:

networks:
  caddy-network:
    name: caddy-network
    external: true
